"""add labels column to cards

Revision ID: ba0c86bc10a1
Revises: 4bc6ad32f0c9
Create Date: 2025-12-10 02:23:13.086048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0c86bc10a1'
down_revision: Union[str, None] = '4bc6ad32f0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_2'), 'activity_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_1'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'boards', ['board_id'], ['id'])
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_1'), 'automations', type_='foreignkey')
    op.create_foreign_key(None, 'automations', 'boards', ['board_id'], ['id'])
    op.drop_constraint(op.f('fk_1'), 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('cards', sa.Column('labels', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('fk_1'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'lists', ['list_id'], ['id'])
    op.drop_constraint(op.f('fk_2'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('fk_1'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'cards', ['card_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_1'), 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'boards', ['board_id'], ['id'])
    op.drop_constraint(op.f('fk_2'), 'roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_1'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles', 'boards', ['board_id'], ['id'])
    op.drop_constraint(op.f('fk_1'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'workspaces', 'users', ['owner_id'], ['id'], referent_schema='flowboard')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'roles', 'boards', ['board_id'], ['id'], referent_schema='flowboard')
    op.create_foreign_key(op.f('fk_2'), 'roles', 'users', ['user_id'], ['id'], referent_schema='flowboard')
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'lists', 'boards', ['board_id'], ['id'], referent_schema='flowboard')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'comments', 'cards', ['card_id'], ['id'], referent_schema='flowboard')
    op.create_foreign_key(op.f('fk_2'), 'comments', 'users', ['user_id'], ['id'], referent_schema='flowboard')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'cards', 'lists', ['list_id'], ['id'], referent_schema='flowboard')
    op.drop_column('cards', 'labels')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'boards', 'workspaces', ['workspace_id'], ['id'], referent_schema='flowboard')
    op.drop_constraint(None, 'automations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'automations', 'boards', ['board_id'], ['id'], referent_schema='flowboard')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_1'), 'activity_logs', 'boards', ['board_id'], ['id'], referent_schema='flowboard')
    op.create_foreign_key(op.f('fk_2'), 'activity_logs', 'users', ['user_id'], ['id'], referent_schema='flowboard')
    # ### end Alembic commands ###

